<%@ Page Title="" Language="C#" MasterPageFile="~/WebsiteAsp.master" AutoEventWireup="true" CodeBehind="AspVS.aspx.cs" Inherits="assignement5.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AspPlaceHolder" runat="server">
          <p>
              <b>Microsoft Visual Studio</b> is an <a href="https://en.wikipedia.org/wiki/Integrated_development_environment" title="Integrated development environment">integrated development environment</a> (IDE) from <a href="https://en.wikipedia.org/wiki/Microsoft" title="Microsoft">Microsoft</a>. It is used to develop <a href="https://en.wikipedia.org/wiki/Computer_program" title="Computer program">computer programs</a> for <a href="https://en.wikipedia.org/wiki/Microsoft_Windows" title="Microsoft Windows">Microsoft Windows</a>, as well as <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Web_site" title="Web site">web sites</a>, <a href="https://en.wikipedia.org/wiki/Web_application" title="Web application">web applications</a> and <a href="https://en.wikipedia.org/wiki/Web_service" title="Web service">web services</a>. Visual Studio uses Microsoft software development platforms such as <a href="https://en.wikipedia.org/wiki/Windows_API" title="Windows API">Windows API</a>,
              <a href="https://en.wikipedia.org/wiki/Windows_Forms" title="Windows Forms">Windows Forms</a>, <a href="https://en.wikipedia.org/wiki/Windows_Presentation_Foundation" title="Windows Presentation Foundation">Windows Presentation Foundation</a>, <a href="https://en.wikipedia.org/wiki/Windows_Store" title="Windows Store">Windows Store</a> and <a href="https://en.wikipedia.org/wiki/Microsoft_Silverlight" title="Microsoft Silverlight">Microsoft Silverlight</a>. It can produce both <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Native_code" title="Native code">native code</a> and <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a>.</p>
          <p>
              Visual Studio includes a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Code_editor" title="Code editor">code editor</a> supporting <a class="mw-redirect" href="https://en.wikipedia.org/wiki/IntelliSense" title="IntelliSense">IntelliSense</a> (the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Code_completion" title="Code completion">code completion</a> component) as well as <a href="https://en.wikipedia.org/wiki/Code_refactoring" title="Code refactoring">code refactoring</a>. The integrated <a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio_Debugger" title="Microsoft Visual Studio Debugger">debugger</a> works both as a source-level debugger and a machine-level debugger. Other built-in tools include a forms designer for building <a class="mw-redirect" href="https://en.wikipedia.org/wiki/GUI" title="GUI">GUI</a> applications, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Web_designer" title="Web designer">web designer</a>,
              <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Class_(computing%2529" title="Class (computing)">class</a> designer, and <a href="https://en.wikipedia.org/wiki/Database_schema" title="Database schema">database schema</a> designer. It accepts plug-ins that enhance the functionality at almost every level—including adding support for <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Source_control" title="Source control">source-control</a> systems (like <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Subversion_(software%2529" title="Subversion (software)">Subversion</a>) and adding new toolsets like editors and visual designers for <a href="https://en.wikipedia.org/wiki/Domain-specific_language" title="Domain-specific language">domain-specific languages</a> or toolsets for other aspects of the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Software_development_lifecycle" title="Software development lifecycle">software development lifecycle</a> 
              (like the <a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">Team Foundation Server</a> client: Team Explorer).</p>
          <p>
              Visual Studio supports different <a href="https://en.wikipedia.org/wiki/Programming_language" title="Programming language">programming languages</a> and allows the code editor and debugger to support (to varying degrees) nearly any programming language, provided a language-specific service exists. Built-in languages include <a href="https://en.wikipedia.org/wiki/C_(programming_language%2529" title="C (programming language)">C</a>,<sup id="cite_ref-5" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-5"><span>[</span>5<span>]</span></a></sup> <a href="https://en.wikipedia.org/wiki/C++" title="C++">C++</a> and <a href="https://en.wikipedia.org/wiki/C++/CLI" title="C++/CLI">C++/CLI</a> (via <a href="https://en.wikipedia.org/wiki/Visual_C++" title="Visual C++">Visual C++</a>), <a class="mw-redirect" href="https://en.wikipedia.org/wiki/VB.NET" title="VB.NET">VB.NET</a> (via
              <a href="https://en.wikipedia.org/wiki/Visual_Basic_.NET" title="Visual Basic .NET">Visual Basic .NET</a>), <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language%2529" title="C Sharp (programming language)">C#</a> (via <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_C_Sharp" title="Visual C Sharp">Visual C#</a>), and <a href="https://en.wikipedia.org/wiki/F_Sharp_(programming_language%2529" title="F Sharp (programming language)">F#</a> (as of Visual Studio 2010<sup id="cite_ref-6" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-6"><span>[</span>6<span>]</span></a></sup>). Support for other languages such as <a href="https://en.wikipedia.org/wiki/MUMPS" title="MUMPS">M</a>, <a href="https://en.wikipedia.org/wiki/IronPython" title="IronPython">Python</a>, and <a href="https://en.wikipedia.org/wiki/IronRuby" title="IronRuby">Ruby</a> among others is available via language services installed separately. It also 
              supports <a href="https://en.wikipedia.org/wiki/XML" title="XML">XML</a>/<a href="https://en.wikipedia.org/wiki/XSLT" title="XSLT">XSLT</a>, <a href="https://en.wikipedia.org/wiki/HTML" title="HTML">HTML</a>/<a href="https://en.wikipedia.org/wiki/XHTML" title="XHTML">XHTML</a>, <a href="https://en.wikipedia.org/wiki/JavaScript" title="JavaScript">JavaScript</a> and <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets" title="Cascading Style Sheets">CSS</a>. Java (and J#) were supported in the past.</p>
          <p>
              Microsoft provides &quot;Community&quot; editions of its Visual Studio at no cost. Commercial versions of Visual Studio along with select past versions are available for free to students via Microsoft&#39;s <a href="https://en.wikipedia.org/wiki/DreamSpark" title="DreamSpark">DreamSpark</a> program.<sup id="cite_ref-7" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-7"><span>[</span>7<span>]</span></a></sup></p>
          <p>
              Microsoft provides a preview of <a href="https://en.wikipedia.org/wiki/Visual_Studio_Code" title="Visual Studio Code">Visual Studio Code</a> for free with a proprietary license.<sup id="cite_ref-Visual_Studio_Blog_8-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-Visual_Studio_Blog-8"><span>[</span>8<span>]</span></a></sup> It is a source code and text editor, along with other features, for Linux, OS X, and Windows.</p>
          <h2><span id="Architecture" class="mw-headline">Architecture</span></h2>
          <p>
              Visual Studio does not support any programming language, solution or tool intrinsically; instead, it allows the plugging of functionality coded as a VSPackage. When installed, the functionality is available as a <i>Service</i>. The IDE provides three services: SVsSolution, which provides the ability to enumerate projects and solutions; SVsUIShell, which provides windowing and UI functionality (including tabs, toolbars and tool windows); and SVsShell, which deals with registration of VSPackages. In addition, the IDE is also responsible for coordinating and enabling communication between services.<sup id="cite_ref-vsenviron_10-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vsenviron-10"><span>[</span>10<span>]</span></a></sup> All editors, designers, project types and other tools are implemented as VSPackages. Visual Studio uses <a href="https://en.wikipedia.org/wiki/Component_Object_Model" title="Component Object Model">COM</a> to access 
              the VSPackages. The Visual Studio <a href="https://en.wikipedia.org/wiki/Software_development_kit" title="Software development kit">SDK</a> also includes the <i>Managed Package Framework</i> (<i>MPF</i>), which is a set of <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed</a> wrappers around the COM-interfaces that allow the Packages to be written in any <a href="https://en.wikipedia.org/wiki/List_of_CLI_languages" title="List of CLI languages">CLI compliant language</a>.<sup id="cite_ref-11" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-11"><span>[</span>11<span>]</span></a></sup> However, MPF does not provide all the functionality exposed by the Visual Studio COM interfaces.<sup id="cite_ref-extpage1_12-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-extpage1-12"><span>[</span>12<span>]</span></a></sup> The services can then be consumed for creation of other 
              packages, which add functionality to the Visual Studio IDE.</p>
          <p>
              Support for programming languages is added by using a specific VSPackage called a <i>Language Service</i>. A language service defines various interfaces which the VSPackage implementation can implement to add support for various functionalities.<sup id="cite_ref-langserv_13-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-langserv-13"><span>[</span>13<span>]</span></a></sup> Functionalities that can be added this way include syntax coloring, statement completion, brace matching, parameter information tooltips, member lists and error markers for background compilation.<sup id="cite_ref-langserv_13-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-langserv-13"><span>[</span>13<span>]</span></a></sup> If the interface is implemented, the functionality will be available for the language. Language services are to be implemented on a per-language basis. The implementations can reuse code from the parser 
              or the compiler for the language.<sup id="cite_ref-langserv_13-2" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-langserv-13"><span>[</span>13<span>]</span></a></sup> Language services can be implemented either in <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Native_code" title="Native code">native code</a> or <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a>. For native code, either the native COM interfaces or the Babel Framework (part of Visual Studio SDK) can be used.<sup id="cite_ref-14" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-14"><span>[</span>14<span>]</span></a></sup> For managed code, the MPF includes wrappers for writing managed language services.<sup id="cite_ref-15" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-15"><span>[</span>15<span>]</span></a></sup></p>
          <p>
              Visual Studio does not include any <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Source_control" title="Source control">source control</a> support built in but it defines two alternative ways for source control systems to integrate with the IDE.<sup id="cite_ref-scci_16-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-scci-16"><span>[</span>16<span>]</span></a></sup> A Source Control VSPackage can provide its own customised user interface. In contrast, a source control plugin using the <i>MSSCCI</i> (Microsoft Source Code Control Interface) provides a set of functions that are used to implement various source control functionality, with a standard Visual Studio user interface.<sup id="cite_ref-17" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-17"><span>[</span>17<span>]</span></a></sup><sup id="cite_ref-alan_18-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-alan-18"><span>[</span>18<span>]</span></a></sup> 
              MSSCCI was first used to integrate <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_SourceSafe" title="Visual SourceSafe">Visual SourceSafe</a> with Visual Studio 6.0 but was later opened up via the Visual Studio SDK. Visual Studio .NET 2002 used MSSCCI 1.1, and Visual Studio .NET 2003 used MSSCCI 1.2. Visual Studio 2005, 2008 and 2010 use MSSCCI Version 1.3, which adds support for rename and delete propagation as well as asynchronous opening.<sup id="cite_ref-alan_18-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-alan-18"><span>[</span>18<span>]</span></a></sup></p>
          <p>
              Visual Studio supports running multiple instances of the environment (each with its own set of VSPackages). The instances use different <a href="https://en.wikipedia.org/wiki/Windows_Registry" title="Windows Registry">registry hives</a> (see <a class="mw-redirect" href="https://en.wikipedia.org/wiki/MSDN" title="MSDN">MSDN</a>&#39;s <a class="external text" href="https://msdn.microsoft.com/en-us/library/ms724877(VS.85).aspx" rel="nofollow">definition</a> of the term &quot;registry <b>hive</b>&quot; in the sense used here) to store their configuration state and are differentiated by their AppId (Application ID). The instances are launched by an AppId-specific .exe that selects the AppId, sets the root hive and launches the IDE. VSPackages registered for one AppId are integrated with other VSPackages for that AppId. The various product editions of Visual Studio are created using the different AppIds. The
              <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_Studio_Express" title="Visual Studio Express">Visual Studio Express</a> edition products are installed with their own AppIds, but the Standard, Professional and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_Studio_Team_System" title="Visual Studio Team System">Team Suite</a> products share the same AppId. Consequently, one can install the Express editions side-by-side with other editions, unlike the other editions which update the same installation. The professional edition includes a superset of the VSPackages in the standard edition and the team suite includes a superset of the VSPackages in both other editions. The AppId system is leveraged by the <a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#Extensibility">Visual Studio Shell</a> in Visual Studio 2008.<sup id="cite_ref-codefocus_19-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-codefocus-19"><span>[</span>19<span>]</span></a></sup></p>
          <h2><span id="Features" class="mw-headline">Features</span></h2>
          <h3><span id="Code_editor" class="mw-headline">Code editor</span></h3>
          <p>
              Like any other <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Integrated_Development_Environment" title="Integrated Development Environment">IDE</a>, it includes a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Code_editor" title="Code editor">code editor</a> that supports <a href="https://en.wikipedia.org/wiki/Syntax_highlighting" title="Syntax highlighting">syntax highlighting</a> and <a href="https://en.wikipedia.org/wiki/Autocomplete" title="Autocomplete">code completion</a> using <a class="mw-redirect" href="https://en.wikipedia.org/wiki/IntelliSense" title="IntelliSense">IntelliSense</a> for <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Variable_(programming%2529" title="Variable (programming)">variables</a>, <a href="https://en.wikipedia.org/wiki/Subroutine" title="Subroutine">functions</a>, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Method_(computer_science%2529" title="Method (computer science)">methods</a>,
              <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Program_loops" title="Program loops">loops</a> and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/LINQ" title="LINQ">LINQ</a> queries.<sup id="cite_ref-vs2008editor_20-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vs2008editor-20"><span>[</span>20<span>]</span></a></sup> IntelliSense is supported for the included languages, as well as for <a href="https://en.wikipedia.org/wiki/XML" title="XML">XML</a> and for <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets" title="Cascading Style Sheets">Cascading Style Sheets</a> and <a href="https://en.wikipedia.org/wiki/JavaScript" title="JavaScript">JavaScript</a> when developing web sites and <a href="https://en.wikipedia.org/wiki/Web_application" title="Web application">web applications</a>.<sup id="cite_ref-vs2008js_21-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vs2008js-21"><span>[</span>21<span>]</span></a></sup><sup id="cite_ref-vs2008css_22-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vs2008css-22"><span>[</span>22<span>]</span></a></sup> 
              Autocomplete suggestions appear in a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Modeless" title="Modeless">modeless</a> <a href="https://en.wikipedia.org/wiki/List_box" title="List box">list box</a> over the code editor window, in proximity of the editing <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cursor_(computing%2529" title="Cursor (computing)">cursor</a>. In Visual Studio 2008 onwards, it can be made temporarily semi-transparent to see the code obstructed by it.<sup id="cite_ref-vs2008editor_20-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vs2008editor-20"><span>[</span>20<span>]</span></a></sup> The code editor is used for all supported languages.</p>
          <p>
              The Visual Studio code editor also supports setting bookmarks in code for quick navigation. Other navigational aids include <a href="https://en.wikipedia.org/wiki/Code_folding" title="Code folding">collapsing code blocks</a> and <a href="https://en.wikipedia.org/wiki/Incremental_search" title="Incremental search">incremental search</a>, in addition to normal text search and <a href="https://en.wikipedia.org/wiki/Regular_expression" title="Regular expression">regex</a> search.<sup id="cite_ref-feat_23-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-feat-23"><span>[</span>23<span>]</span></a></sup> The code editor also includes a multi-item <a href="https://en.wikipedia.org/wiki/Clipboard" title="Clipboard">clipboard</a> and a task list.<sup id="cite_ref-feat_23-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-feat-23"><span>[</span>23<span>]</span></a></sup> The code editor supports code 
              snippets, which are saved templates for repetitive code and can be inserted into code and customized for the project being worked on. A management tool for code snippets is built in as well. These tools are surfaced as floating windows which can be set to automatically hide when unused or docked to the side of the screen. The Visual Studio code editor also supports <a href="https://en.wikipedia.org/wiki/Code_refactoring" title="Code refactoring">code refactoring</a> including parameter reordering, variable and method renaming, <a href="https://en.wikipedia.org/wiki/Interface_(computing%2529" title="Interface (computing)">interface</a> extraction and encapsulation of class members inside properties, among others.</p>
          <p>
              Visual Studio features background compilation (also called incremental compilation).<sup id="cite_ref-bgcompile_24-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-bgcompile-24"><span>[</span>24<span>]</span></a></sup><sup id="cite_ref-advbasics_25-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-advbasics-25"><span>[</span>25<span>]</span></a></sup> As code is being written, Visual Studio compiles it in the background in order to provide feedback about syntax and compilation errors, which are flagged with a red wavy underline. Warnings are marked with a green underline. Background compilation does not generate executable code, since it requires a different compiler than the one used to generate executable code.<sup id="cite_ref-26" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-26"><span>[</span>26<span>]</span></a></sup> Background compilation was 
              initially introduced with <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Microsoft_Visual_Basic" title="Microsoft Visual Basic">Microsoft Visual Basic</a> but has now been expanded for all included languages.<sup id="cite_ref-advbasics_25-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-advbasics-25"><span>[</span>25<span>]</span></a></sup></p>
          <h3><span id="Debugger" class="mw-headline">Debugger</span></h3>
          <div class="hatnote relarticle mainarticle">
              Main article: <a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio_Debugger" title="Microsoft Visual Studio Debugger">Microsoft Visual Studio Debugger</a></div>
          <p>
              Visual Studio includes a <a href="https://en.wikipedia.org/wiki/Debugger" title="Debugger">debugger</a> that works both as a source-level debugger and as a machine-level debugger. It works with both <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a> as well as <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Native_code" title="Native code">native code</a> and can be used for debugging applications written in any language supported by Visual Studio. In addition, it can also attach to running processes and monitor and debug those processes.<sup id="cite_ref-27" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-27"><span>[</span>27<span>]</span></a></sup> If source code for the running process is available, it displays the code as it is being run. If source code is not available, it can show the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Disassembly" title="Disassembly">disassembly</a>. 
              The Visual Studio debugger can also create <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Memory_dump" title="Memory dump">memory dumps</a> as well as load them later for debugging.<sup id="cite_ref-28" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-28"><span>[</span>28<span>]</span></a></sup> Multi-threaded programs are also supported. The debugger can be configured to be launched when an application running outside the Visual Studio environment crashes.</p>
          <p>
              The debugger allows setting <a href="https://en.wikipedia.org/wiki/Breakpoint" title="Breakpoint">breakpoints</a> (which allow execution to be stopped temporarily at a certain position) and watches (which monitor the values of variables as the execution progresses).<sup id="cite_ref-29" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-29"><span>[</span>29<span>]</span></a></sup> Breakpoints can be conditional, meaning they get triggered when the condition is met. Code can be <a href="https://en.wikipedia.org/wiki/Program_animation" title="Program animation">stepped over</a>, i.e., run one line (of source code) at a time.<sup id="cite_ref-step_30-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-step-30"><span>[</span>30<span>]</span></a></sup> It can either <i>step into</i> functions to debug inside it, or <i>step over</i> it, i.e., the execution of the function body isn&#39;t available for manual 
              inspection.<sup id="cite_ref-step_30-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-step-30"><span>[</span>30<span>]</span></a></sup> The debugger supports <i>Edit and Continue</i>, i.e., it allows code to be edited as it is being debugged. When debugging, if the mouse pointer hovers over any variable, its current value is displayed in a tooltip (&quot;data tooltips&quot;), where it can also be modified if desired. During coding, the Visual Studio debugger lets certain functions be invoked manually from the <code>Immediate</code> tool window. The parameters to the method are supplied at the Immediate window.<sup id="cite_ref-31" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-31"><span>[</span>31<span>]</span></a></sup></p>
          <h3><span id="Designer" class="mw-headline">Designer</span></h3>
          <p>
              Visual Studio includes a host of visual designers to aid in the development of applications. These tools include:</p>
          <dl>
              <dt>Windows Forms Designer</dt>
              <dd>The Windows Forms designer is used to build <a class="mw-redirect" href="https://en.wikipedia.org/wiki/GUI" title="GUI">GUI</a> applications using <a class="mw-redirect" href="https://en.wikipedia.org/wiki/WinForms" title="WinForms">Windows Forms</a>. Layout can be controlled by housing the controls inside other containers or locking them to the side of the form. Controls that display data (like textbox, list box, grid view, etc.) can be <a href="https://en.wikipedia.org/wiki/Data_binding" title="Data binding">bound</a> to data sources like <a href="https://en.wikipedia.org/wiki/Database" title="Database">databases</a> or <a class="mw-redirect" href="https://en.wikipedia.org/wiki/LINQ" title="LINQ">queries</a>. Data-bound controls can be created by dragging items from the Data Sources window onto a design surface.<sup id="cite_ref-32" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-32"><span>[</span>32<span>]</span></a></sup> The UI is linked 
                  with code using an <a href="https://en.wikipedia.org/wiki/Event-driven_programming" title="Event-driven programming">event-driven programming</a> model. The designer generates either <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language%2529" title="C Sharp (programming language)">C#</a> or <a class="mw-redirect" href="https://en.wikipedia.org/wiki/VB.NET" title="VB.NET">VB.NET</a> code for the application.</dd>
              <dt>WPF Designer</dt>
              <dd>The WPF designer, codenamed <i>Cider</i>,<sup id="cite_ref-33" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-33"><span>[</span>33<span>]</span></a></sup> was introduced with Visual Studio 2008. Like the Windows Forms designer it supports the drag and drop metaphor. It is used to author <a href="https://en.wikipedia.org/wiki/User_interface" title="User interface">user interfaces</a> targeting <a href="https://en.wikipedia.org/wiki/Windows_Presentation_Foundation" title="Windows Presentation Foundation">Windows Presentation Foundation</a>. It supports all WPF functionality including <a href="https://en.wikipedia.org/wiki/Data_binding" title="Data binding">data binding</a> and automatic layout management. It generates <a class="mw-redirect" href="https://en.wikipedia.org/wiki/XAML" title="XAML">XAML</a> code for the UI. The generated <a class="mw-redirect" href="https://en.wikipedia.org/wiki/XAML" title="XAML">XAML</a> file is compatible with
                  <a href="https://en.wikipedia.org/wiki/Microsoft_Expression_Design" title="Microsoft Expression Design">Microsoft Expression Design</a>, the designer-oriented product. The XAML code is linked with code using a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Code-behind" title="Code-behind">code-behind</a> model.</dd>
              <dt>Web designer/development</dt>
              <dd>Visual Studio also includes a web-site editor and designer that allows web pages to be authored by dragging and dropping widgets. It is used for developing <a href="https://en.wikipedia.org/wiki/ASP.NET" title="ASP.NET">ASP.NET</a> applications and supports <a href="https://en.wikipedia.org/wiki/HTML" title="HTML">HTML</a>, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/CSS" title="CSS">CSS</a> and <a href="https://en.wikipedia.org/wiki/JavaScript" title="JavaScript">JavaScript</a>. It uses a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Code-behind" title="Code-behind">code-behind</a> model to link with ASP.NET code. From Visual Studio 2008 onwards, the layout engine used by the web designer is shared with <a href="https://en.wikipedia.org/wiki/Microsoft_Expression_Web" title="Microsoft Expression Web">Microsoft Expression Web</a>. There is also <a class="mw-redirect" href="https://en.wikipedia.org/wiki/ASP.NET_MVC" title="ASP.NET MVC">ASP.NET MVC</a> support 
                  for <a href="https://en.wikipedia.org/wiki/Model–view–controller" title="Model–view–controller">MVC</a> technology as a separate download<sup id="cite_ref-34" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-34"><span>[</span>34<span>]</span></a></sup> and <a href="https://en.wikipedia.org/wiki/ASP.NET_Dynamic_Data" title="ASP.NET Dynamic Data">ASP.NET Dynamic Data</a> project available from Microsoft.<sup id="cite_ref-35" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-35"><span>[</span>35<span>]</span></a></sup></dd>
              <dt>Class designer</dt>
              <dd>The Class Designer is used to author and edit the classes (including its members and their access) using <a href="https://en.wikipedia.org/wiki/Unified_Modeling_Language" title="Unified Modeling Language">UML</a> modeling. The Class Designer can generate <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language%2529" title="C Sharp (programming language)">C#</a> and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/VB.NET" title="VB.NET">VB.NET</a> code outlines for the classes and methods. It can also generate class diagrams from hand-written classes.</dd>
              <dt>Data designer</dt>
              <dd>The data designer can be used to graphically edit <a href="https://en.wikipedia.org/wiki/Database_schema" title="Database schema">database schemas</a>, including typed tables, primary and foreign keys and constraints. It can also be used to design queries from the graphical view.</dd>
              <dt>Mapping designer</dt>
              <dd>From Visual Studio 2008 onwards, the mapping designer is used by <a href="https://en.wikipedia.org/wiki/Language_Integrated_Query" title="Language Integrated Query">LINQ to SQL</a> to design the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Object-Relational_mapping" title="Object-Relational mapping">mapping</a> between <a href="https://en.wikipedia.org/wiki/Database_schema" title="Database schema">database schemas</a> and the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Class_(computing%2529" title="Class (computing)">classes</a> that encapsulate the data. The new solution from ORM approach, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/ADO.NET_Entity_Framework" title="ADO.NET Entity Framework">ADO.NET Entity Framework</a>, replaces and improves the old technology.</dd>
          </dl>
          <h3><span id="Other_tools" class="mw-headline">Other tools</span></h3>
          <dl>
              <dt>Open Tabs Browser</dt>
              <dd>The open tabs browser is used to list all open tabs and to switch between them. It is invoked using <code>CTRL+TAB</code>.</dd>
              <dt>Properties Editor</dt>
              <dd>The <i>Properties Editor</i> tool is used to edit properties in a GUI pane inside Visual Studio. It lists all available properties (both read-only and those which can be set) for all objects including <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Class_(computing%2529" title="Class (computing)">classes</a>, forms, web pages and other items.</dd>
              <dt>Object Browser</dt>
              <dd>The <i>Object Browser</i> is a <a href="https://en.wikipedia.org/wiki/Namespace" title="Namespace">namespace</a> and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Class_library" title="Class library">class library</a> browser for <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Microsoft_.NET" title="Microsoft .NET">Microsoft .NET</a>. It can be used to browse the namespaces (which are arranged hierarchically) in <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed</a> <a href="https://en.wikipedia.org/wiki/Assembly_(CLI%2529" title="Assembly (CLI)">assemblies</a>. The hierarchy may or may not reflect the organization in the file system.</dd>
              <dt>Solution Explorer</dt>
              <dd>In Visual Studio parlance, a solution is a set of code files and other resources that are used to build an application. The files in a solution are arranged hierarchically, which might or might not reflect the organization in the file system. The <i>Solution Explorer</i> is used to manage and browse the files in a solution.</dd>
              <dt>Team Explorer</dt>
              <dd><i>Team Explorer</i> is used to integrate the capabilities of <a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">Team Foundation Server</a>, the <a href="https://en.wikipedia.org/wiki/Revision_Control_System" title="Revision Control System">Revision Control System</a> into the IDE (and the basis for Microsoft&#39;s <a href="https://en.wikipedia.org/wiki/CodePlex" title="CodePlex">CodePlex</a> hosting environment for open source projects). In addition to source control it provides the ability to view and manage individual work items (including bugs, tasks and other documents) and to browse <a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">TFS</a> statistics. It is included as part of a TFS install and is also available as a download for Visual Studio separately.<sup id="cite_ref-36" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-36"><span>[</span>36<span>]</span></a></sup><sup id="cite_ref-37" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-37"><span>[</span>37<span>]</span></a></sup> 
                  Team Explorer is also available as a stand-alone environment solely to access TFS services.</dd>
              <dt>Data Explorer</dt>
              <dd><i>Data Explorer</i> is used to manage databases on <a href="https://en.wikipedia.org/wiki/Microsoft_SQL_Server" title="Microsoft SQL Server">Microsoft SQL Server</a> instances. It allows creation and alteration of database tables (either by issuing <a class="mw-redirect" href="https://en.wikipedia.org/wiki/T-SQL" title="T-SQL">T-SQL</a> commands or by using the Data designer). It can also be used to create <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Database_query" title="Database query">queries</a> and <a href="https://en.wikipedia.org/wiki/Stored_procedure" title="Stored procedure">stored procedures</a>, with the latter in either <a class="mw-redirect" href="https://en.wikipedia.org/wiki/T-SQL" title="T-SQL">T-SQL</a> or in <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a> via <a href="https://en.wikipedia.org/wiki/SQL_CLR" title="SQL CLR">SQL CLR</a>. Debugging and
                  <a class="mw-redirect" href="https://en.wikipedia.org/wiki/IntelliSense" title="IntelliSense">IntelliSense</a> support is available as well.</dd>
              <dt>Server Explorer</dt>
              <dd>The <i>Server Explorer</i> tool is used to manage database connections on an accessible computer. It is also used to browse running <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Windows_Service" title="Windows Service">Windows Services</a>, performance counters, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Windows_Event_Log" title="Windows Event Log">Windows Event Log</a> and <a href="https://en.wikipedia.org/wiki/Message_queue" title="Message queue">message queues</a> and use them as a datasource.<sup id="cite_ref-38" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-38"><span>[</span>38<span>]</span></a></sup></dd>
              <dt>Dotfuscator Software Services Community Edition</dt>
              <dd>Visual Studio includes a free &#39;light&#39; version of <a href="https://en.wikipedia.org/wiki/Dotfuscator" title="Dotfuscator">Dotfuscator</a> by <a class="new" href="https://en.wikipedia.org/w/index.php?title=PreEmptive_Solutions&amp;action=edit&amp;redlink=1" title="PreEmptive Solutions (page does not exist)">PreEmptive Solutions</a> which performs code obfuscation and application size reduction.<sup id="cite_ref-39" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-39"><span>[</span>39<span>]</span></a></sup> Starting with Visual Studio 2010, this version of Dotfuscator includes <a href="https://en.wikipedia.org/wiki/Runtime_intelligence" title="Runtime intelligence">runtime intelligence</a> capabilities that allow authors to gather end-user usage, performance, and stability information from their applications running in production.<sup id="cite_ref-40" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-40"><span>[</span>40<span>]</span></a></sup></dd>
              <dt>Text Generation Framework</dt>
              <dd>Visual Studio includes a full text generation framework called <a href="https://en.wikipedia.org/wiki/Text_Template_Transformation_Toolkit" title="Text Template Transformation Toolkit">T4</a> which enables Visual Studio to generate text files from templates either in the IDE or via code.</dd>
              <dt>ASP.NET Web Site Administration Tool</dt>
              <dd>The <a href="https://en.wikipedia.org/wiki/ASP.NET_Web_Site_Administration_Tool" title="ASP.NET Web Site Administration Tool">ASP.NET Web Site Administration Tool</a> allows for the configuration of <a href="https://en.wikipedia.org/wiki/ASP.NET" title="ASP.NET">ASP.NET</a> websites.</dd>
              <dt>Visual Studio Tools for Office</dt>
              <dd><a href="https://en.wikipedia.org/wiki/Visual_Studio_Tools_for_Office" title="Visual Studio Tools for Office">Visual Studio Tools for Office</a> is a SDK and an add-in for Visual Studio that includes tools for developing for the <a href="https://en.wikipedia.org/wiki/Microsoft_Office" title="Microsoft Office">Microsoft Office</a> suite. Previously (for Visual Studio .NET 2003 and Visual Studio 2005) it was a separate SKU that supported only <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_C_Sharp" title="Visual C Sharp">Visual C#</a> and <a href="https://en.wikipedia.org/wiki/Visual_Basic_.NET" title="Visual Basic .NET">Visual Basic</a> languages or was included in the Team Suite. With Visual Studio 2008, it is no longer a separate SKU but is included with Professional and higher editions. A separate runtime is required when deploying VSTO solutions.</dd>
          </dl>
          <h3><span id="Extensibility" class="mw-headline">Extensibility</span></h3>
          <div class="hatnote">
              See also: <a class="mw-redirect" href="https://en.wikipedia.org/wiki/List_of_Microsoft_Visual_Studio_Add-ins" title="List of Microsoft Visual Studio Add-ins">List of Microsoft Visual Studio Add-ins</a> and <a href="https://en.wikipedia.org/wiki/Visual_Studio_Extensibility" title="Visual Studio Extensibility">Visual Studio Extensibility</a></div>
          <p>
              Visual Studio allows developers to write extensions for Visual Studio to extend its capabilities. These extensions &quot;plug into&quot; Visual Studio and extend its functionality. Extensions come in the form of <i>macros</i>, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/List_of_Microsoft_Visual_Studio_Add-ins" title="List of Microsoft Visual Studio Add-ins"><i>add-ins</i></a>, and <i>packages</i>. Macros represent repeatable tasks and actions that developers can record programmatically for saving, replaying, and distributing. Macros, however, cannot implement new commands or create tool windows. They are written using <a href="https://en.wikipedia.org/wiki/Visual_Basic" title="Visual Basic">Visual Basic</a> and are not compiled.<sup id="cite_ref-extpage1_12-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-extpage1-12"><span>[</span>12<span>]</span></a></sup> Add-Ins provide access to the Visual Studio object model and can interact with 
              the IDE tools. Add-Ins can be used to implement new functionality and can add new tool windows. Add-Ins are plugged into the IDE via <a href="https://en.wikipedia.org/wiki/Component_Object_Model" title="Component Object Model">COM</a> and can be created in any COM-compliant languages.<sup id="cite_ref-extpage1_12-2" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-extpage1-12"><span>[</span>12<span>]</span></a></sup> Packages are created using the Visual Studio <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Software_Development_Kit" title="Software Development Kit">SDK</a> and provide the highest level of extensibility. They can create designers and other tools, as well as integrate other programming languages. The Visual Studio SDK provides unmanaged <a class="mw-redirect" href="https://en.wikipedia.org/wiki/API" title="API">APIs</a> as well as a managed API to accomplish these tasks. However, the managed API isn&#39;t as 
              comprehensive as the unmanaged one.<sup id="cite_ref-extpage1_12-3" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-extpage1-12"><span>[</span>12<span>]</span></a></sup> Extensions are supported in the Standard (and higher) versions of Visual Studio 2005. <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_Studio_Express" title="Visual Studio Express">Express Editions</a> do not support hosting extensions.</p>
          <p>
              Visual Studio 2008 introduced the <b>Visual Studio Shell</b> that allows for development of a customized version of the IDE. The Visual Studio Shell defines a set of VSPackages that provide the functionality required in any IDE. On top of that, other packages can be added to customize the installation. The Isolated mode of the shell creates a new AppId where the packages are installed. These are to be started with a different executable. It is aimed for development of custom development environments, either for a specific language or a specific scenario. The Integrated mode installs the packages into the AppId of the Professional/Standard/Team System editions, so that the tools integrate into these editions.<sup id="cite_ref-codefocus_19-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-codefocus-19"><span>[</span>19<span>]</span></a></sup> The Visual Studio Shell is available as a free download.</p>
          <p>
              After the release of Visual Studio 2008, Microsoft created the Visual Studio Gallery. It serves as the central location for posting information about extensions to Visual Studio. Community developers as well as commercial developers can upload information about their extensions to Visual Studio .NET 2002 through Visual Studio 2010. Users of the site can rate and review the extensions to help assess the quality of extensions being posted. RSS feeds to notify users on updates to the site and tagging features are also planned.<sup id="cite_ref-41" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-41"><span>[</span>41<span>]</span></a></sup></p>
          <h2><span id="Supported_products" class="mw-headline">Supported products</span></h2>
          <dl>
              <dt><a href="https://en.wikipedia.org/wiki/Visual_C++" title="Visual C++">Microsoft Visual C++</a></dt>
              <dd>Microsoft Visual C++ is Microsoft&#39;s implementation of the <a href="https://en.wikipedia.org/wiki/C_(programming_language%2529" title="C (programming language)">C</a> and <a href="https://en.wikipedia.org/wiki/C++" title="C++">C++</a> <a href="https://en.wikipedia.org/wiki/Compiler" title="Compiler">compiler</a> and associated languages-services and specific tools for integration with the Visual Studio IDE. It can compile either in C mode or C++ mode. For C, it follows the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/C90_(C_version%2529" title="C90 (C version)">ISO C</a> standard with parts of <a href="https://en.wikipedia.org/wiki/C99" title="C99">C99</a> specification along with MS-specific additions in the form of libraries.<sup id="cite_ref-42" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-42"><span>[</span>42<span>]</span></a></sup> For C++, it follows the
                  <a class="mw-redirect" href="https://en.wikipedia.org/wiki/ANSI_C++" title="ANSI C++">ANSI C++</a> specification along with a few <a href="https://en.wikipedia.org/wiki/C++11" title="C++11">C++11</a> features.<sup id="cite_ref-43" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-43"><span>[</span>43<span>]</span></a></sup> It also supports the <a href="https://en.wikipedia.org/wiki/C++/CLI" title="C++/CLI">C++/CLI</a> specification to write <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a>, as well as mixed-mode code (a mix of <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Native_code" title="Native code">native</a> and <a href="https://en.wikipedia.org/wiki/Managed_code" title="Managed code">managed code</a>). Microsoft positions Visual C++ for development in native code or in code that contains both native as well as managed components. Visual C++ supports
                  <a href="https://en.wikipedia.org/wiki/Component_Object_Model" title="Component Object Model">COM</a> as well as the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Microsoft_Foundation_Classes" title="Microsoft Foundation Classes">MFC</a> library. For MFC development, it provides a set of wizards for creating and customizing MFC <a href="https://en.wikipedia.org/wiki/Boilerplate_code" title="Boilerplate code">boilerplate code</a>, and creating GUI applications using MFC. Visual C++ can also use the Visual Studio forms designer to design UI graphically. Visual C++ can also be used with the <a href="https://en.wikipedia.org/wiki/Windows_API" title="Windows API">Windows API</a>. It also supports the use of <i>intrinsic functions</i>,<sup id="cite_ref-44" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-44"><span>[</span>44<span>]</span></a></sup> which are functions recognized by the compiler itself and not implemented as a library. 
                  Intrinsic functions are used to expose the <a href="https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions" title="Streaming SIMD Extensions">SSE</a> instruction set of modern CPUs. Visual C++ also includes the <a href="https://en.wikipedia.org/wiki/OpenMP" title="OpenMP">OpenMP</a> (version 2.0) specification.<sup id="cite_ref-45" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-45"><span>[</span>45<span>]</span></a></sup></dd>
              <dt><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_C_Sharp" title="Visual C Sharp">Microsoft Visual C#</a></dt>
              <dd>Microsoft Visual C#, Microsoft&#39;s implementation of the <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language%2529" title="C Sharp (programming language)">C#</a> language, targets the .NET Framework, along with the language services that lets the Visual Studio IDE support C# projects. While the language services are a part of Visual Studio, the compiler is available separately as a part of the .NET Framework. The Visual C# 2008, 2010 and 2012 compilers support versions 3.0, 4.0 and 5.0 of the C# language specifications, respectively. Visual C# supports the Visual Studio Class designer, Forms designer, and Data designer among others.<sup id="cite_ref-46" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-46"><span>[</span>46<span>]</span></a></sup></dd>
              <dt><a href="https://en.wikipedia.org/wiki/Visual_Basic_.NET" title="Visual Basic .NET">Microsoft Visual Basic</a></dt>
              <dd>Microsoft Visual Basic is Microsoft&#39;s implementation of the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/VB.NET" title="VB.NET">VB.NET</a> language and associated tools and language services. It was introduced with Visual Studio .NET (2002). Microsoft has positioned Visual Basic for <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Rapid_Application_Development" title="Rapid Application Development">Rapid Application Development</a>.<sup id="cite_ref-47" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-47"><span>[</span>47<span>]</span></a></sup><sup id="cite_ref-48" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-48"><span>[</span>48<span>]</span></a></sup> Visual Basic can be used to author both console applications as well as GUI applications. Like Visual C#, Visual Basic also supports the Visual Studio Class designer, Forms designer, and Data designer among others. Like C#, 
                  the VB.NET compiler is also available as a part of .NET Framework, but the language services that let VB.NET projects be developed with Visual Studio, are available as a part of the latter.</dd>
              <dt>Microsoft Visual Web Developer</dt>
              <dd>Microsoft Visual Web Developer is used to create web sites, <a href="https://en.wikipedia.org/wiki/Web_application" title="Web application">web applications</a> and <a href="https://en.wikipedia.org/wiki/Web_service" title="Web service">web services</a> using ASP.NET. Either <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language%2529" title="C Sharp (programming language)">C#</a> or <a class="mw-redirect" href="https://en.wikipedia.org/wiki/VB.NET" title="VB.NET">VB.NET</a> languages can be used. Visual Web Developer can use the Visual Studio Web Designer to graphically design web page layouts.</dd>
              <dt><a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">Team Foundation Server</a></dt>
              <dd>Included only with <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_Studio_Team_System" title="Visual Studio Team System">Visual Studio Team System</a>, Team Foundation Server is intended for collaborative <a href="https://en.wikipedia.org/wiki/Software_development" title="Software development">software development</a> projects and acts as the server-side backend providing <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Source_control" title="Source control">source control</a>, data collection, <a href="https://en.wikipedia.org/wiki/Report" title="Report">reporting</a>, and project-tracking functionality. It also includes the <i>Team Explorer</i>, the client tool for <a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">TFS</a> services, which is integrated inside Visual Studio Team System.</dd>
          </dl>
          <h3><span id="Previous_products" class="mw-headline">Previous products</span></h3>
          <dl>
              <dt><a href="https://en.wikipedia.org/wiki/Visual_FoxPro" title="Visual FoxPro">Visual FoxPro</a></dt>
              <dd>Visual FoxPro is a data-centric <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Object-oriented" title="Object-oriented">object-oriented</a> and <a href="https://en.wikipedia.org/wiki/Procedural_programming" title="Procedural programming">procedural</a> <a href="https://en.wikipedia.org/wiki/Programming_language" title="Programming language">programming language</a> produced by <a href="https://en.wikipedia.org/wiki/Microsoft" title="Microsoft">Microsoft</a>. It derives from <a class="mw-redirect" href="https://en.wikipedia.org/wiki/FoxPro_2" title="FoxPro 2">FoxPro</a> (originally known as <b>FoxBASE</b>) which was developed by Fox Software beginning in 1984. Visual FoxPro is tightly integrated with its own relational database engine, which extends FoxPro&#39;s xBase capabilities to support <a href="https://en.wikipedia.org/wiki/SQL" title="SQL">SQL</a> queries and data manipulation. Visual FoxPro is a full-featured,<sup id="cite_ref-49" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-49"><span>[</span>49<span>]</span></a></sup>
                  <a href="https://en.wikipedia.org/wiki/Dynamic_programming_language" title="Dynamic programming language">dynamic programming language</a> that does not require the use of an additional general-purpose programming environment. In 2007, Visual FoxPro was discontinued after version 9 Service Pack 2. It was supported until 2015.<sup id="cite_ref-50" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-50"><span>[</span>50<span>]</span></a></sup></dd>
          </dl>
          <dl>
              <dt><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_SourceSafe" title="Visual SourceSafe">Visual SourceSafe</a></dt>
              <dd>Microsoft Visual SourceSafe is a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Source_control" title="Source control">source control</a> <a href="https://en.wikipedia.org/wiki/Software" title="Software">software</a> package oriented towards small software-development projects. The SourceSafe database is a multi-user, multi-process file-system database, using the Windows file system database primitives to provide locking and sharing support. All versions are multi-user, using <a href="https://en.wikipedia.org/wiki/Server_Message_Block" title="Server Message Block">SMB</a> (file server) networking.<sup id="cite_ref-51" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-51"><span>[</span>51<span>]</span></a></sup><sup id="cite_ref-52" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-52"><span>[</span>52<span>]</span></a></sup><sup id="cite_ref-53" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-53"><span>[</span>53<span>]</span></a></sup> 
                  However, with Visual SourceSafe 2005, other <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Client–server" title="Client–server">client–server</a> modes were added, Lan Booster and VSS Internet (which used <a class="mw-redirect" href="https://en.wikipedia.org/wiki/HTTP" title="HTTP">HTTP</a>/<a href="https://en.wikipedia.org/wiki/HTTPS" title="HTTPS">HTTPS</a>). Visual SourceSafe 6.0 was available as a stand-alone product<sup id="cite_ref-54" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-54"><span>[</span>54<span>]</span></a></sup> and was included with Visual Studio 6.0, and other products such as Office Developer Edition. Visual SourceSafe 2005 was available as a stand-alone product and included with the 2005 Team Suite. <a href="https://en.wikipedia.org/wiki/Team_Foundation_Server" title="Team Foundation Server">Team Foundation Server</a> has superseded VSS as Microsoft&#39;s recommended platform for
                  <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Source_control" title="Source control">source control</a>.</dd>
          </dl>
          <dl>
              <dt><a href="https://en.wikipedia.org/wiki/Visual_J++" title="Visual J++">Microsoft Visual J++</a>/<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_J_Sharp" title="Visual J Sharp">Microsoft Visual J#</a></dt>
              <dd>Microsoft Visual J++ was <a href="https://en.wikipedia.org/wiki/Microsoft" title="Microsoft">Microsoft</a>&#39;s implementation of the <a href="https://en.wikipedia.org/wiki/Java_(programming_language%2529" title="Java (programming language)">Java</a> language (with Microsoft-specific extensions) and associated language services. It was discontinued as a result of <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sun_Microsystems_vs._Microsoft" title="Sun Microsystems vs. Microsoft">litigation</a> from <a href="https://en.wikipedia.org/wiki/Sun_Microsystems" title="Sun Microsystems">Sun Microsystems</a>, and the technology was recycled into Visual J#, Microsoft&#39;s Java compiler for .NET Framework. J# was available with Visual Studio 2005 (supported until 2015) but was discontinued in Visual Studio 2008.</dd>
          </dl>
          <dl>
              <dt><a href="https://en.wikipedia.org/wiki/Visual_InterDev" title="Visual InterDev">Visual InterDev</a></dt>
              <dd>Visual InterDev was used to create web applications using Microsoft <a href="https://en.wikipedia.org/wiki/Active_Server_Pages" title="Active Server Pages">Active Server Pages</a> (ASP) technologies. It supports code completion and includes <a href="https://en.wikipedia.org/wiki/Database" title="Database">database</a> server management tools. It has been replaced with Microsoft Visual Web Developer.</dd>
          </dl>
          <h2><span id="Editions" class="mw-headline">Editions</span></h2>
          <p>
              Microsoft Visual Studio is available in the following editions or <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Stock-keeping_unit" title="Stock-keeping unit">SKUs</a>:<sup id="cite_ref-Visual_Studio_Editions_55-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-Visual_Studio_Editions-55"><span>[</span>55<span>]</span></a></sup></p>
          <h3><span id="Visual_Studio_Community" class="mw-headline">Visual Studio Community</span></h3>
          <p>
              On 12 November 2014, Microsoft announced Visual Studio Community, a new free version similar in functionality to Visual Studio Professional. Unlike Express, Visual Studio Community supports multiple languages, and provides support for extensions. Visual Studio Community is oriented towards individual developers and small teams.<sup id="cite_ref-vb-vscommunity_56-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vb-vscommunity-56"><span>[</span>56<span>]</span></a></sup><sup id="cite_ref-vb-vscommunity2_57-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-vb-vscommunity2-57"><span>[</span>57<span>]</span></a></sup></p>
          <h3><span id="Visual_Studio_Professional" class="mw-headline">Visual Studio Professional</span></h3>
          <p>
              Visual Studio Professional Edition provides an IDE for all supported development languages. As of Visual Studio 2010, the Standard edition was dropped.<sup id="cite_ref-VS_2010_Licensing_Changes_58-0" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-VS_2010_Licensing_Changes-58"><span>[</span>58<span>]</span></a></sup> <a class="mw-redirect" href="https://en.wikipedia.org/wiki/MSDN" title="MSDN">MSDN</a> support is available as MSDN Essentials or the full <a class="mw-redirect" href="https://en.wikipedia.org/wiki/MSDN_library" title="MSDN library">MSDN library</a> depending on licensing. It supports <a href="https://en.wikipedia.org/wiki/XML" title="XML">XML</a> and <a href="https://en.wikipedia.org/wiki/XSLT" title="XSLT">XSLT</a> editing, and can create deployment packages that only use <a href="https://en.wikipedia.org/wiki/ClickOnce" title="ClickOnce">ClickOnce</a> and
              <a href="https://en.wikipedia.org/wiki/Windows_Installer" title="Windows Installer">MSI</a>. It includes tools like Server Explorer and integration with <a href="https://en.wikipedia.org/wiki/Microsoft_SQL_Server" title="Microsoft SQL Server">Microsoft SQL Server</a> also. Windows Mobile development support was included in Visual Studio 2005 Standard, however, with Visual Studio 2008, it is only available in Professional and higher editions. Windows Phone 7 development support was added to all editions in Visual Studio 2010. Development for <a href="https://en.wikipedia.org/wiki/Windows_Mobile" title="Windows Mobile">Windows Mobile</a> is no longer supported in Visual Studio 2010; it is superseded by <a href="https://en.wikipedia.org/wiki/Windows_Phone_7" title="Windows Phone 7">Windows Phone 7</a>.</p>
          <h3><span id="Visual_Studio_Enterprise" class="mw-headline">Visual Studio Enterprise</span></h3>
          <p>
              Visual Studio Enterprise provides a set of software and database development, collaboration, metrics, architecture, testing and reporting tools in addition to the features provided by Visual Studio Professional.</p>
          <h3><span id="Visual_Studio_Test_Professional" class="mw-headline">Visual Studio Test Professional</span></h3>
          <p>
              Visual Studio Test Professional is an edition which was introduced with Visual Studio 2010. Its focus is aimed at the dedicated tester role and includes support for the management of test environments, the ability to start and report on tests and to connect to Team Foundation Server. It does not include support for development or authoring of tests.<sup id="cite_ref-Visual_Studio_Editions_55-1" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-Visual_Studio_Editions-55"><span>[</span>55<span>]</span></a></sup></p>
          <h3><span id="Visual_Studio_Express" class="mw-headline">Visual Studio Express</span></h3>
          <p>
              <a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio_Express" title="Microsoft Visual Studio Express">Visual Studio Express Editions</a> are a set of free lightweight individual IDEs which are provided as stripped-down versions of the Visual Studio IDE on a per-platform basis or per-language basis, i.e., it installs the development tools for the supported platforms (web, Windows, phone) or supported development languages (VB, C#) onto individual Visual Studio Shell AppIds. It includes only a small set of tools as compared to the other systems. Versions prior to 2013 Update 2 do not include support for plug-ins. <a href="https://en.wikipedia.org/wiki/X86-64" title="X86-64">x64</a> compilers are not included in the Visual Studio Express edition IDEs, but are available as part of a Windows Software Development Kit that can be installed separately.<sup id="cite_ref-59" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-59"><span>[</span>59<span>]</span></a></sup> 
              After an initial announcement<sup id="cite_ref-60" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-60"><span>[</span>60<span>]</span></a></sup> that the Express 2012 release would be restricted to creating <a href="https://en.wikipedia.org/wiki/Windows_8" title="Windows 8">Windows 8</a> <a href="https://en.wikipedia.org/wiki/Metro_(design_language%2529" title="Metro (design language)">Metro</a>-style applications, Microsoft responded to negative developer feedback by reversing that decision and announcing that desktop application development would also be supported.<sup id="cite_ref-61" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-61"><span>[</span>61<span>]</span></a></sup> Microsoft targets the Express IDEs at students and hobbyists. Express editions do not use the full <a class="mw-redirect" href="https://en.wikipedia.org/wiki/MSDN_Library" title="MSDN Library">MSDN Library</a> but use the MSDN 
              Essentials Library. The languages available as part of the Express IDEs are:<sup id="cite_ref-62" class="reference"><a href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#cite_note-62"><span>[</span>62<span>]</span></a></sup></p>
          <ul>
              <li>Visual Basic Express</li>
              <li>Visual C++ Express</li>
              <li>Visual C# Express</li>
              <li>Visual Web Developer Express</li>
              <li>Express for Windows Phone</li>
          </ul>
          <p>
              &nbsp;</p>
          <h1></h1>
</asp:Content>
